# Generated by Django 2.2.3 on 2019-07-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gousto_reference", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=160)),
                ("short_title", models.CharField(blank=True, max_length=80, null=True)),
                ("calories_kcal", models.PositiveIntegerField(default=0)),
                ("protein_grams", models.PositiveIntegerField(default=0)),
                ("fat_grams", models.PositiveIntegerField(default=0)),
                ("carbs_grams", models.PositiveIntegerField(default=0)),
                (
                    "bulletpoint1",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "bulletpoint2",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "bulletpoint3",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("recipe_diet_type_id", models.CharField(max_length=20)),
                ("season", models.CharField(default="all", max_length=10)),
                ("base", models.CharField(max_length=30)),
                ("protein_source", models.CharField(max_length=30)),
                ("preparation_time_minutes", models.PositiveIntegerField()),
                ("shelf_life_days", models.PositiveIntegerField()),
                ("equipment_needed", models.CharField(max_length=30)),
                ("origin_country", models.CharField(max_length=30)),
                ("recipe_cuisine", models.CharField(max_length=30)),
                ("in_your_box", models.TextField(blank=True, null=True)),
                ("box_type", models.CharField(max_length=30)),
                ("marketing_description", models.TextField()),
                ("slug", models.SlugField(max_length=150)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "recipe",
                "verbose_name_plural": "recipes",
                "db_table": "recipe",
            },
        )
    ]
